using Microsoft.CodeAnalysis;

namespace DotNetDo.Generators;

[Generator]
public sealed class MSBuildRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(output => output.AddSource("DotNetDo.MSBuildRegistration.g.cs", Source));

    const string Source = """
        // <auto-generated />
        namespace DotNetDo.Generated;

        static class MSBuildRegistration
        {
            [global::System.Runtime.CompilerServices.ModuleInitializer]
            internal static void Initialize()
            {
                if (!global::Microsoft.Build.Locator.MSBuildLocator.IsRegistered)
                    global::Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults();
            }
        }
        """;
}
